version: "2"
services:
  semantic-enrichment:
    image: iasistest.atc.gr:444/semantic_enrichment:latest
    hostname: semantic-enrichment
    container_name: iasis_semantic_enrichment
    domainname: iasiskg
    volumes:
      - ./data:/data/data
      - ./rdf/output:/data/output
      - ./settings/configs:/data/configs
      - ./settings/mappings:/data/mappings
      - ./gdown.pl:/data/gdown.pl
    env_file:
      - ./envfile.env
    depends_on:
      - iasis_genomic_kgstore
      - iasis_lc_notes_kgstore
      - iasis_drug_pub_kgstore
      - iasis_lc_images_kgstore
    networks:
      - iasiskg

  iasis_genomic_kgstore:
    image: asakor/virtuoso:7-max
    hostname: iasis_genomic_kgstore
    container_name: iasis_genomic_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/genomic:/data
      - ./rdf/output/genomic:/data/output/genomic
    ports:
      - "11381:8890"
      - "1112:1111"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  iasis_lc_images_kgstore:
    image: asakor/virtuoso:7-max
    hostname: iasis_lc_images_kgstore
    container_name: iasis_lc_images_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/lc_images:/data
      - ./rdf/output/lc_images:/data/output/lc_images
    ports:
      - "11382:8890"
      - "1113:1111"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  iasis_lc_notes_kgstore:
    image: asakor/virtuoso:7-max
    hostname: iasis_lc_notes_kgstore
    container_name: iasis_lc_notes_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/lc_notes:/data
      - ./rdf/output/lc_notes:/data/output/lc_notes
    ports:
      - "11383:8890"
      - "1114:1111"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  iasis_drug_pub_kgstore:
    image: asakor/virtuoso:7-max
    hostname: iasis_drug_pub_kgstore
    container_name: iasis_drug_pub_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/drug_pub:/data
      - ./rdf/output/drug_pub:/data/output/drug_pub
    ports:
      - "11384:8890"
      - "1115:1111"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  iasis_dementia_kgstore:
    image: asakor/virtuoso:7-max
    hostname: iasis_dementia_kgstore
    container_name: iasis_dementia_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/drug_pub:/data
      - ./rdf/output/dementia:/data/output/dementia
    ports:
      - "11385:8890"
      - "1116:1111"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  ontario:
    image: iasistest.atc.gr:444/ontario:latest
    hostname: ontario
    container_name: iasis_ontario
    domainname: iasiskg
    volumes:
      - ./settings/ontario:/data
    ports:
      - "5025:5000"
    environment:
      - RABBITMQ_IP=10.114.113.14
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg



networks:
  iasiskg:
    external: true
