version: "2"
services:
  semantic-enrichment:
    image: iasistest.atc.gr/semantic_enrichment:latest
    hostname: semantic-enrichment
    container_name: iasis_semantic_enrichment
    domainname: iasiskg
    volumes:
      - ./data:/data/data
      - ./rdf/output:/data/output
      - ./settings/configs:/data/configs
      - ./settings/mappings:/data/mappings
      - ./gdown.pl:/data/gdown.pl
    env_file:
      - ./envfile.env
    depends_on:
      - iasis_genomic_kgstore
      - iasis_lc_notes_kgstore
      - iasis_drug_pub_kgstore
    networks:
      - iasiskg

  iasis_genomic_kgstore:
    image: kemele/virtuoso:7-stable
    hostname: iasis_genomic_kgstore
    container_name: iasis_genomic_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/genomic:/data
      - ./rdf/output/genomic:/data/output/genomic
    ports:
      - "11381:8890"
      - "1112:1111"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg


  iasis_lc_notes_kgstore:
    image: kemele/virtuoso:7-stable
    hostname: iasis_lc_notes_kgstore
    container_name: iasis_lc_notes_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/lc_notes:/data
      - ./rdf/output/lc_notes:/data/output/lc_notes
    ports:
      - "11382:8890"
      - "1113:1111"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  iasis_drug_pub_kgstore:
    image: kemele/virtuoso:7-stable
    hostname: iasis_drug_pub_kgstore
    container_name: iasis_drug_pub_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf/drug_pub:/data
      - ./rdf/output/drug_pub:/data/output/drug_pub
    ports:
      - "11383:8890"
      - "1114:1111"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg
      
  ontario:
    image: iasistest.atc.gr/ontario:latest
    hostname: ontario
    container_name: iasis_ontario
    domainname: iasiskg
    volumes:
      - ./settings/ontario:/data
    ports:
      - "5025:5000"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg

  semepnode:
    image: iasistest.atc.gr/semep:latest
    hostname: semepnode
    container_name: iasis_semepnode
    domainname: iasiskg
    ports:
      - "5026:5001"
    environment:
      - IASISKG_ENDPOINT=http://iasis_lc_notes_kgstore:8890/sparql
    depends_on:
      - iasis_lc_notes_kgstore
    networks:
      - iasiskg

  drugexploration:
    image: iasistest.atc.gr/drug_exploration:latest
    hostname: drugexploration
    container_name: iasis_drugexploration
    domainname: iasiskg
    ports:
      - "5027:5002"
    environment:
      - IASISKG_ENDPOINT=http://iasis_drug_pub_kgstore:8890/sparql
    depends_on:
      - iasis_drug_pub_kgstore
    networks:
      - iasiskg

  lc_exploration:
    image: iasistest.atc.gr/lc_exploration:latest
    hostname: lc_exploration
    container_name: iasis_lc_exploration
    domainname: iasiskg
    ports:
      - "5028:5003"
    environment:
      - IASISKG_ENDPOINT=http://iasis_drug_pub_kgstore:8890/sparql
    depends_on:
      - iasis_drug_pub_kgstore
    networks:
      - iasiskg


networks:
  iasiskg:
    external: true
