version: "2"
services:
  semantic-enrichment:
    image: kemele/semantic_enrichment:1.0
    hostname: semantic-enrichment
    container_name: iasis_semantic_enrichment
    domainname: iasiskg
    volumes:
      - ./data:/data/data
      - ./rdf/output:/data/output
      - ./settings/configs:/data/configs
      - ./settings/mappings:/data/mappings
    env_file:
      - ./settings/envfile.env
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  iasiskgstore:
    image: kemele/virtuoso:6-stable
    hostname: iasiskgstore
    container_name: iasis_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf:/data
    ports:
      - "11381:8890"
      - "1112:1111"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg

  ontario:
    image: kemele/mulder:1.0
    hostname: ontario
    container_name: iasis_ontario
    domainname: iasiskg
    volumes:
      - ./settings/ontario:/data
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  semepnode:
    image: palma/semepnode:1.0
    hostname: semepnode
    container_name: iasis_semepnode
    domainname: iasiskg
    ports:
      - "5001:5001"
    environment:
      - IASISKG_ENDPOINT=http://iasiskgstore:8890/sparql
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  drugexploration:
    image: palma/drug_exploration:1.0
    hostname: drugexploration
    container_name: iasis_drugexploration
    domainname: iasiskg
    ports:
      - "5002:5002"
    environment:
      - IASISKG_ENDPOINT=http://iasiskgstore:8890/sparql
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg


networks:
  iasiskg:
    external: true
