version: "2"
services:
  semantic-enrichment:
    image: iasistest.atc.gr/semantic_enrichment:latest
    hostname: semantic-enrichment
    container_name: iasis_semantic_enrichment
    domainname: iasiskg
    volumes:
      - ./data:/data/data
      - ./rdf/output:/data/output
      - ./settings/configs:/data/configs
      - ./settings/mappings:/data/mappings
      - ./gdown.pl:/data/gdown.pl
    env_file:
      - ./envfile.env
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  iasiskgstore:
    image: kemele/virtuoso:6-stable
    hostname: iasiskgstore
    container_name: iasis_kgstore
    domainname: iasiskg
    volumes:
      - ./rdf:/data
    ports:
      - "11381:8890"
      - "1112:1111"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    networks:
      - iasiskg

  ontario:
    image: iasistest.atc.gr/ontario:latest
    hostname: ontario
    container_name: iasis_ontario
    domainname: iasiskg
    volumes:
      - ./settings/ontario:/data
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_IP=10.115.83.18
      - RABBITMQ_PORT=5672
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  semepnode:
    image: iasistest.atc.gr/semep:latest
    hostname: semepnode
    container_name: iasis_semepnode
    domainname: iasiskg
    ports:
      - "5001:5001"
    environment:
      - IASISKG_ENDPOINT=http://iasiskgstore:8890/sparql
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  drugexploration:
    image: iasistest.atc.gr/drug_exploration:latest
    hostname: drugexploration
    container_name: iasis_drugexploration
    domainname: iasiskg
    ports:
      - "5002:5002"
    environment:
      - IASISKG_ENDPOINT=http://iasiskgstore:8890/sparql
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg

  lc_exploration:
    image: iasistest.atc.gr/lc_exploration:latest
    hostname: lc_exploration
    container_name: iasis_lc_exploration
    domainname: iasiskg
    ports:
      - "5003:5003"
    environment:
      - IASISKG_ENDPOINT=http://iasiskgstore:8890/sparql
    depends_on:
      - iasiskgstore
    networks:
      - iasiskg


networks:
  iasiskg:
    external: true
